version: '2'
 
services:
  mysql:
    image: mysql
    container_name: mysql_compose
    ports:
      - 6603:3306
    environment:
      MYSQL_ROOT_PASSWORD: "45612300"
    volumes:
      - /storage/docker/mysql-datadir:/var/lib/mysql
